In [1]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_excel("Khorezm Dialect (++ENG).xlsx", index_col="№")
df.head()

,Khorezm dialect form of the word,Latin Translation,District of using this dialect word (within Khorezm region),Official form (in Cyrillic Uzbek),Latin Translation.1,Translation of the official form,Unnamed: 7
№,,,,,,,
1,абзал,abzal,All,афзал,afzal,preferable; superior; more advantageous,NaN
2,авъзламақ,avʼzlamaq,Mangit; Gurlan; Yangibozor,Мавжуд эмас,Mavjud emas,Not attested,NaN
3,авъртмақ,avʼrtmaq,Mangit; Gurlan; Yangibozor,Мавжуд эмас,Mavjud emas,Not attested,NaN
4,айдън,aydʼn,Gurlan; Yangibozor,1. ойдин ; 2. кулниг қамишсиз чукур жойи,1. oydin ; 2. kulnig qamishsiz chukur joyi,"1) moonlit, clear 2) deep hollow of the palm (...",NaN
5,айық,ayiq,Gurlan; Yangibozor,"уйғоқ; тетик, хушёр",uygʼoq; tetik,"awake; alert, vigilant",NaN

In [6]:
columns_to_dop = [
    "Khorezm dialect form of the word", 
    "District of using this dialect word (within Khorezm region)", 
    "Official form (in Cyrillic Uzbek)", 
    "Translation of the official form", 
    "Unnamed: 7"
]
df.drop(columns=columns_to_dop, inplace=True)

In [7]:
df.columns

Index(['Latin Translation', 'Latin Translation.1'], dtype='str')

In [8]:
df.head()

  Latin Translation                         Latin Translation.1
№
1             abzal                                       afzal
2         avʼzlamaq                                 Mavjud emas
3          avʼrtmaq                                 Mavjud emas
4             aydʼn  1. oydin ; 2. kulnig qamishsiz chukur joyi
5              ayiq                               uygʼoq; tetik

In [9]:
df = df.rename(columns={
    'Latin Translation': 'dialect',
    'Latin Translation.1': 'literary'
})
df.head()

     dialect                                    literary
№
1      abzal                                       afzal
2  avʼzlamaq                                 Mavjud emas
3   avʼrtmaq                                 Mavjud emas
4      aydʼn  1. oydin ; 2. kulnig qamishsiz chukur joyi
5       ayiq                               uygʼoq; tetik

In [10]:
df.describe

<bound method NDFrame.describe of          dialect                                    literary
№
1          abzal                                       afzal
2      avʼzlamaq                                 Mavjud emas
3       avʼrtmaq                                 Mavjud emas
4          aydʼn  1. oydin ; 2. kulnig qamishsiz chukur joyi
5           ayiq                               uygʼoq; tetik
...          ...                                         ...
1336  shunchaqlʼ                                     shuncha
1337   shүnchәll                                  shunchalik
1338   shүndәtip                                shunday etib
1339     shүntip                               shunday qilib
1340     shүttik                                   jinchiroq

[1340 rows x 2 columns]>

In [12]:
df['literary'].value_counts()

literary
Mavjud emas       105
yigʼmoq             4
dөvmәk              3
ya:va               3
aryan               2
                 ...
shuncha             1
shunchalik          1
shunday etib        1
 shunday qilib      1
jinchiroq           1
Name: count, Length: 1180, dtype: int64

In [13]:
df = df.replace("Mavjud emas", np.nan)
df['literary'].value_counts()

literary
yigʼmoq           4
dөvmәk            3
ya:va             3
aryan             2
ip                2
                 ..
shuncha           1
shunchalik        1
shunday etib      1
 shunday qilib    1
jinchiroq         1
Name: count, Length: 1179, dtype: int64